sha not working
wallet_inittiation error:

    sha = hashlib.sha256(entropy)
TypeError: object supporting the buffer API required

entropy is encoded 128 bit int